export default function Home() {export default function Home() {
  return (
      <main style={{ minHeight: "100vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "24px", position: "relative", zIndex: 1, textAlign: "center" }}>
            <div style={{ display: "inline-flex", alignItems: "center", gap: "8px", background: "rgba(255, 51, 102, 0.1)", border: "1px solid rgba(255, 51, 102, 0.3)", padding: "8px 16px", borderRadius: "100px", fontSize: "13px", color: "#ff7799", marginBottom: "32px", fontWeight: 500 }}>
                    🚧 MVP under construction
                          </div>
                                <h1 style={{ fontSize: "clamp(40px, 7vw, 76px)", fontWeight: 900, lineHeight: 1.1, marginBottom: "24px", letterSpacing: "-2px", maxWidth: "900px" }}>
                                        Quickthumb is <span style={{ background: "var(--gradient)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>coming soon</span>.
                                              </h1>
                                                    <p style={{ fontSize: "clamp(16px, 2vw, 20px)", color: "var(--text-muted)", maxWidth: "560px", marginBottom: "40px" }}>
                                                            Paste a YouTube URL. Our AI watches the video and generates 4 click-tested thumbnails in 60 seconds.
                                                                  </p>
                                                                        <a href="https://quickthumb.app" style={{ background: "var(--gradient)", color: "white", padding: "16px 32px", borderRadius: "100px", textDecoration: "none", fontWeight: 700, fontSize: "16px", boxShadow: "0 8px 32px rgba(255, 51, 102, 0.4)" }}>
                                                                                Join the waitlist →
                                                                                      </a>
                                                                                            <footer style={{ marginTop: "80px", color: "var(--text-muted)", fontSize: "13px" }}>
                                                                                                    Building in public · Solo dev · <a href="https://x.com/Quickthumb_app" target="_blank" rel="noopener noreferrer" style={{ color: "var(--accent)" }}>@Quickthumb_app</a>
                                                                                                          </footer>
                                                                                                              </main>
                                                                                                                );
                                                                                                                }
                                                                                                                
  return (
      <main
            style={{
                    minHeight: "100vh",
                            display: "flex",
                                    flexDirection: "column",
                                            alignItems: "center",
                                                    justifyContent: "center",
                                                            padding: "24px",
                                                                    position: "relative",
                                                                            zIndex: 1,
                                                                                    textAlign: "center",
                                                                                          }}
                                                                                              >
                                                                                                    <div
                                                                                                            style={{
                                                                                                                      display: "inline-flex",
                                                                                                                                alignItems: "center",
                                                                                                                                          gap: "8px",
                                                                                                                                                    background: "rgba(255, 51, 102, 0.1)",
                                                                                                                                                              border: "1px solid rgba(255, 51, 102, 0.3)",
                                                                                                                                                                        padding: "8px 16px",
                                                                                                                                                                                  borderRadius: "100px",
                                                                                                                                                                                            fontSize: "13px",
                                                                                                                                                                                                      color: "#ff7799",
                                                                                                                                                                                                                marginBottom: "32px",
                                                                                                                                                                                                                          fontWeight: 500,
                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                🚧 MVP under construction
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                            <h1
                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                              fontSize: "clamp(40px, 7vw, 76px)",
                                                                                                                                                                                                                                                                                        fontWeight: 900,
                                                                                                                                                                                                                                                                                                  lineHeight: 1.1,
                                                                                                                                                                                                                                                                                                            marginBottom: "24px",
                                                                                                                                                                                                                                                                                                                      letterSpacing: "-2px",
                                                                                                                                                                                                                                                                                                                                maxWidth: "900px",
                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                      Quickthumb is{" "}
                                                                                                                                                                                                                                                                                                                                                              <span
                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                    background: "var(--gradient)",
                                                                                                                                                                                                                                                                                                                                                                                                WebkitBackgroundClip: "text",
                                                                                                                                                                                                                                                                                                                                                                                                            WebkitTextFillColor: "transparent",
                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundClip: "text",
                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                    coming soon
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: "clamp(16px, 2vw, 20px)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: "var(--text-muted)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      maxWidth: "560px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: "40px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Paste a YouTube URL. Our AI watches the video and generates 4 click-tested thumbnails in 60 seconds.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href="https://quickthumb.app"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "var(--gradient)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "16px 32px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "100px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  boxShadow: "0 8px 32px rgba(255, 51, 102, 0.4)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Join the waitlist →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <footer style={{ marginTop: "80px", color: "var(--text-muted)", fontSize: "13px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Building in public · Solo dev ·{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="https://x.com/Quickthumb_app" target="_blank" rel="noopener noreferrer" style={{ color: "var(--accent)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              @Quickthumb_app
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
